// Code generated by protoc-gen-go. DO NOT EDIT.
// source: resourceupdate.proto

package resourceupdate

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UpdateRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PodName              string   `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	ContainerName        string   `protobuf:"bytes,3,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	Memory               int64    `protobuf:"varint,4,opt,name=memory,proto3" json:"memory,omitempty"`
	Cpu                  int64    `protobuf:"varint,5,opt,name=cpu,proto3" json:"cpu,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea66352f32c6655d, []int{0}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *UpdateRequest) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *UpdateRequest) GetContainerName() string {
	if m != nil {
		return m.ContainerName
	}
	return ""
}

func (m *UpdateRequest) GetMemory() int64 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *UpdateRequest) GetCpu() int64 {
	if m != nil {
		return m.Cpu
	}
	return 0
}

type UpdateResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea66352f32c6655d, []int{1}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*UpdateRequest)(nil), "resourceupdate.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "resourceupdate.UpdateResponse")
}

func init() { proto.RegisterFile("resourceupdate.proto", fileDescriptor_ea66352f32c6655d) }

var fileDescriptor_ea66352f32c6655d = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x8d, 0xd1, 0xa4, 0x1d, 0x68, 0x90, 0x45, 0x34, 0x16, 0x95, 0x12, 0x50, 0x7a, 0xca,
	0x41, 0x2f, 0x1e, 0x3c, 0xd5, 0xbb, 0xc8, 0x82, 0x1e, 0xbc, 0x94, 0x75, 0x33, 0xda, 0x62, 0xf7,
	0x8f, 0x3b, 0xbb, 0x07, 0x3f, 0x8a, 0xdf, 0x56, 0xb2, 0x49, 0x94, 0x0a, 0xde, 0xde, 0xbc, 0x79,
	0x0f, 0x7e, 0x3c, 0x38, 0x74, 0x48, 0x26, 0x38, 0x89, 0xc1, 0x36, 0xc2, 0x63, 0x6d, 0x9d, 0xf1,
	0x86, 0x15, 0xdb, 0x6e, 0xf5, 0x95, 0xc0, 0xe4, 0x31, 0x4a, 0x8e, 0x1f, 0x01, 0xc9, 0xb3, 0x53,
	0x18, 0x6b, 0xa1, 0x90, 0xac, 0x90, 0x58, 0x26, 0xb3, 0x64, 0x3e, 0xe6, 0xbf, 0x06, 0x3b, 0x81,
	0x91, 0x35, 0xcd, 0xb2, 0x35, 0xca, 0xdd, 0xf8, 0xcc, 0xad, 0x69, 0xee, 0x85, 0x42, 0x76, 0x01,
	0x85, 0x34, 0xda, 0x8b, 0xb5, 0x46, 0xd7, 0x05, 0xd2, 0x18, 0x98, 0xfc, 0xb8, 0x31, 0x76, 0x04,
	0x99, 0x42, 0x65, 0xdc, 0x67, 0xb9, 0x37, 0x4b, 0xe6, 0x29, 0xef, 0x2f, 0x76, 0x00, 0xa9, 0xb4,
	0xa1, 0xdc, 0x8f, 0x66, 0x2b, 0xab, 0x5b, 0x28, 0x06, 0x34, 0xb2, 0x46, 0x13, 0xb2, 0x12, 0x72,
	0x0a, 0x52, 0x22, 0x51, 0x24, 0x1b, 0xf1, 0xe1, 0x6c, 0xdb, 0x8a, 0xde, 0x7a, 0xa4, 0x56, 0x5e,
	0x21, 0xe4, 0x5d, 0xdb, 0xb1, 0x67, 0x38, 0xee, 0xe4, 0xdd, 0x40, 0xc2, 0xfb, 0x15, 0xd8, 0x59,
	0xfd, 0x67, 0xa6, 0xad, 0x31, 0xa6, 0xe7, 0xff, 0xbd, 0x3b, 0xa0, 0x6a, 0x67, 0x71, 0x09, 0xd3,
	0xb5, 0xa9, 0x57, 0xa8, 0x84, 0xf6, 0xab, 0xfa, 0xfd, 0x86, 0x96, 0x43, 0xe3, 0x35, 0x6c, 0x16,
	0xd9, 0x13, 0x49, 0xb1, 0xc1, 0x87, 0xe4, 0x25, 0x8b, 0xfb, 0x5f, 0x7f, 0x07, 0x00, 0x00, 0xff,
	0xff, 0x90, 0x3d, 0xde, 0x15, 0x97, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UpdaterClient is the client API for Updater service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UpdaterClient interface {
	UpdateContainerResource(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
}

type updaterClient struct {
	cc *grpc.ClientConn
}

func NewUpdaterClient(cc *grpc.ClientConn) UpdaterClient {
	return &updaterClient{cc}
}

func (c *updaterClient) UpdateContainerResource(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/resourceupdate.Updater/UpdateContainerResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdaterServer is the server API for Updater service.
type UpdaterServer interface {
	UpdateContainerResource(context.Context, *UpdateRequest) (*UpdateResponse, error)
}

func RegisterUpdaterServer(s *grpc.Server, srv UpdaterServer) {
	s.RegisterService(&_Updater_serviceDesc, srv)
}

func _Updater_UpdateContainerResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdaterServer).UpdateContainerResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resourceupdate.Updater/UpdateContainerResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdaterServer).UpdateContainerResource(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Updater_serviceDesc = grpc.ServiceDesc{
	ServiceName: "resourceupdate.Updater",
	HandlerType: (*UpdaterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateContainerResource",
			Handler:    _Updater_UpdateContainerResource_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resourceupdate.proto",
}
